heat_template_version: 2015-10-15
description: Launches a standalone GM.
parameters:
  name:
    type: string
    description: the name for the GM
    default: gm
  external_network:
    type: string
    description: the external network for floating IP allocations
    default: public-138-net
    constraints:
      - custom_constraint: neutron.network
  temp_license:
    type: string
    description: comma-delimited list of temp licenses
    default: vnios,enterprise,dns,dhcp,rpz,cloud
  mgmt_network:
    type: string
    description: the management network
    default: mgmt-net
    constraints:
      - custom_constraint: neutron.network
  lan1_network:
    type: string
    description: the protocol network (must have a /24 network for auto addressing to work)
    default: protocol-net
    constraints:
      - custom_constraint: neutron.network
  security_group:
    type: string
    description: the security group to use
    default: Infoblox
  image:
    type: string
    description: NIOS image to use
    default: nios-7.3.0-314102-160G-1420
    constraints:
      - custom_constraint: glance.image
  flavor:
    type: string
    description: NIOS flavor to use (must match image)
    default: vnios-1420.160
    constraints:
      - custom_constraint: nova.flavor
resources:
  lan1_port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: lan1_network}
      security_groups: [{get_param: security_group}]

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: external_network}
      port_id: {get_resource: lan1_port}

  gm:
    type: OS::Nova::Server
    depends_on: [lan1_port]
    properties:
      name: {get_param: name}
      flavor: {get_param: flavor}
      image: {get_param: image}
# The mgmt IP is allocated by OpenStack but not configured in the GM. However,
# we need to list it here since LAN1 needs to be the second NIC
      networks: [{network: {get_param: mgmt_network}}, {port: {get_resource: lan1_port}}]
      config_drive: true
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #infoblox-config
            
            temp_license: $temp_license
            remote_console_enabled: true
            default_admin_password: infoblox
            lan1:
              v4_addr: $v4_addr
              v4_netmask: 255.255.255.0
              v4_gw: $v4_gw
          params:
            $temp_license: { get_param: temp_license }
            $v4_addr: { get_attr: [lan1_port, fixed_ips, 0, ip_address] }
            $v4_gw: { get_attr: [lan1_port, subnets, 0, gateway_ip] }
outputs:
  gm_lan1_ip:
    description: The LAN1 IP address of the GM. Use this as input to the autoscale.yaml stack.
    value: { get_attr: [lan1_port, fixed_ips, 0, ip_address] }
  gm_floating_ip:
    description: The publically accessible floating IP of the GM.
    value: { get_attr: [floating_ip, floating_ip_address] }
